#ifndef __ENUM_H_
#define __ENUM_H_

#define NUM_ARGS_(X9,X8,X7,X6,X5,X4,X3,X2,X1,N,...) N
#define NUM_ARGS(...) NUM_ARGS_(__VA_ARGS__,9,8,7,6,5,4,3,2,1)
#define DECL_CHOICES(ENUM,...) DECL_CHOICES_(NUM_ARGS(__VA_ARGS__),ENUM,__VA_ARGS__)
#define DECL_CHOICES_(N,ENUM,...) DECL_CHOICES__(N,ENUM,__VA_ARGS__)
#define DECL_CHOICES__(N,ENUM,...) DECL_CHOICES_##N(ENUM,__VA_ARGS__)
#define DECL_CHOICES_1(ENUM,CHOICE) ENUM##_##CHOICE
#define DECL_CHOICES_2(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_1(ENUM,__VA_ARGS__)
#define DECL_CHOICES_3(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_2(ENUM,__VA_ARGS__)
#define DECL_CHOICES_4(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_3(ENUM,__VA_ARGS__)
#define DECL_CHOICES_5(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_4(ENUM,__VA_ARGS__)
#define DECL_CHOICES_6(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_5(ENUM,__VA_ARGS__)
#define DECL_CHOICES_7(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_6(ENUM,__VA_ARGS__)
#define DECL_CHOICES_8(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_7(ENUM,__VA_ARGS__)
#define DECL_CHOICES_9(ENUM,CHOICE,...) ENUM##_##CHOICE , DECL_CHOICES_8(ENUM,__VA_ARGS__)

#define MK_ENUM(ENUM,...) \
  typedef struct ENUM { int __value; } ENUM; \
  enum { DECL_CHOICES(ENUM,__VA_ARGS__) }

#define ENUM_EQ(X,VAL) ((X).__value == (VAL))

#define ENUM_SET(X,VAL) do { (X).__value = (VAL); } while(0)

#endif // __ENUM_H_
