#!/bin/bash -eu

CORES_PER_NODE=42
RAM_PER_NODE=200000
GPUS_PER_NODE=6
FB_PER_GPU=15000
source "$SOLEIL_DIR"/src/jobscript_shared.sh

export GASNET_NUM_QPS=1
jsrun -n "$NUM_RANKS" -r "$RANKS_PER_NODE" -a 1 -c "$CORES_PER_RANK" -g "$GPUS_PER_RANK" -b rs \
    $COMMAND

# Resources:
# 2 NUMA domains per node
# 21 cores per NUMA domain (1 more reserved for OS)
# 4-way SMT per core
# 256GB RAM per NUMA domain
# 3 Volta V100 GPUs per NUMA domain
# 16GB FB per GPU
